FedjazContest/FedjazContest/Components/NavbarViewComponent.cs
using FedjazContest.Models;
using Microsoft.AspNetCore.Mvc;

namespace FedjazContest.Components
{
    public class NavbarViewComponent : ViewComponent
    {
        private List<NavbarItem> items = new List<NavbarItem>
        {
            new NavbarItem("Home", "Home"),
            new NavbarItem("About", "Home", "About"),
            new NavbarItem("Creating tasks", "Home", "Creating tasks"),
            new NavbarItem("Contests", "Contests"),
            new NavbarItem("Attempts", "Attempts"),
        };
        public IViewComponentResult Invoke()
        {
            string? controller = ViewContext.RouteData.Values["controller"] as string;
            string? action = ViewContext.RouteData.Values["action"] as string;
            if(controller != null && action != null)
            {
                foreach(NavbarItem item in items)
                {
                    if(item.Controller == controller && item.Action == action)
                    {
                        item.IsActive = true;
                        break;
                    }
                }
            }

            return View(items);
        }
    }
}

FedjazContest/FedjazContest/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FedjazContest</title>
    <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap-grid.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FedjazContest.styles.css" asp-append-version="true" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FedjazContest</a>
                @await Component.InvokeAsync("Navbar")
            </div>
        </nav>
    </header>

    <div class="container-fluid">
        <div class="row">
            <div class="col">
                @if(ViewBag.LeftSection != null)
                {
                    string? leftSection = ViewBag.LeftSection as string;
                    if(leftSection != null)
                    {
                        if(ViewBag.LeftSectionArguments != null)
                        {
                            @await Component.InvokeAsync(leftSection, ViewBag.LeftSectionArguments);
                        }

                        else
                        {
                            @await Component.InvokeAsync(leftSection);
                        }
                    }
                }
            </div>
            <div class="col-7 main-content fill">
                @RenderBody()
            </div>
            <div class="col">
                @await Component.InvokeAsync("Account")
            </div>
        </div>
        
    </div>
        
    <footer class="text-muted ">
        <div class="container p-3">
            &copy; 2022 - FedjazContest - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/jquery.js"></script>
    <script src="~/lib/jquery-validate/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.js"></script>
    <script src="~/lib/font-awesome/js/all.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>